name: 部署到服务器
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/streamlink:latest
          docker stop streamlink-container || true
          docker rm streamlink-container || true
          docker run -d --name streamlink-container \
            -v /path/to/config.ini:/app/config.ini \
            -v /path/to/cookies:/app/cookies \
            -p 6000:6000 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/streamlink:latest
